---
title: "HOW IT ALL BEGAN"
date: 2018-06-26
---

title: Amber's GitHub Journey 
author: Amber Ferrero Laub
email: amberferrerolaub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here's the story of how I learned to use GitHub.

# social links
twitter_username: aferrerolaub
github_username:  amberferrerolaub

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
